  {id:2, title:"Ethiopia and the Valorization of Coffee", date:"2024-10-15", category:"COFFEE", desc:"The Paradox of Abundance: how Ethiopia possesses 6,000 to 10,000 coffee varieties that remain undifferentiated in global markets.", time:"8 min read", body:"Ethiopia possesses an estimated 6,000 to 10,000 distinct varieties of Coffea arabica L., representing approximately 95 percent of the global genetic pool of the species. The southwestern forests \u2014 Kaffa, Bench-Maji, Illubabor \u2014 constitute the natural cradle from which all arabica coffee cultivated worldwide descends. Yet this extraordinary biological wealth functions paradoxically as an undifferentiated mass in the global market.\n\nThe problem is not the absence of diversity."},
  {id:3, title:"Ethiopia's US$6 Billion Coffee Ambition", date:"2026-07-04", category:"COFFEE", desc:"Ethiopia has set an ambitious target of US$6 billion in annual coffee export earnings by 2031.", time:"7 min read", body:"Ethiopia has recorded one of the strongest performances in its coffee export history, generating nearly US$3 billion in foreign exchange from coffee in the 2025/26 fiscal year."},
  {id:4, title:"Germany's Coffee Revolution", date:"2026-05-18", category:"COFFEE", desc:"Germany's coffee market is shifting from commodity consumption toward specialty coffee and origin-focused consumption.", time:"7 min read", body:"Germany's coffee market is undergoing a transformation that extends far beyond traditional commodity trading. Subscription-based coffee platforms now represent 25\u201330 percent of market value."},
  {id:5, title:"Ethiopia and the Global Sesame Market", date:"2024-12-05", category:"SESAME AND OILSEEDS", desc:"Ethiopia faces the structural challenge of value addition rather than raw seed export.", time:"9 min read", body:"Ethiopia occupies a distinctive position in the global sesame market. The worldwide reputation of Humera sesame is well established as one of the country's most desirable export products."},
  {id:6, title:"Ethiopia's Emerging Fruit and Vegetable Export Sector", date:"2026-01-15", category:"FRUITS AND VEGETABLES", desc:"Ethiopia's horticulture sector is growing at 15% annually, driven by demand for avocados and cut flowers.", time:"5 min read", body:"Ethiopia's fruit and vegetable sector has emerged as one of the fastest-growing segments of agricultural exports. Avocado exports grew 240% between 2020 and 2025."},
  {id:7, title:"Teff: Ethiopia's Super Grain Goes Global", date:"2026-02-28", category:"TEFF AND CEREALS", desc:"Teff production reached a record 6.2 million tons in 2025.", time:"6 min read", body:"Teff (Eragrostis tef) is Ethiopia's indigenous staple grain, occupying 3 million hectares of farmland. Production reached 6.2 million tons in 2025."},
  {id:8, title:"Ethiopian Spices: Korarima and Berbere", date:"2026-03-20", category:"SPICES AND AROMATICS", desc:"Ethiopia's spice sector, led by korarima and black cumin, exports to 35 countries.", time:"5 min read", body:"Ethiopia is one of the world's most diverse centers of spice production, with over 20 commercial spice species."},
  {id:9, title:"Ethiopian Honey: Africa's Largest Producer", date:"2026-04-10", category:"HONEY", desc:"Ethiopia produces 65,000 tons of honey annually yet less than 5% is exported.", time:"5 min read", body:"Ethiopia is Africa's largest honey producer with 65,000 tons annually. Export volumes are negligible at less than 3,000 tons."},
  {id:10, title:"EUDR Compliance Roadmap for Ethiopian Exporters", date:"2026-06-15", category:"SUPPLY CHAIN", desc:"A practical guide to achieving EU Deforestation Regulation compliance.", time:"8 min read", body:"The EU Deforestation Regulation requires operators to conduct due diligence proving no deforestation after December 31, 2020."},
  {id:11, title:"Ethiopia's Logistics Corridors", date:"2026-04-05", category:"SUPPLY CHAIN", desc:"A comprehensive overview of Ethiopia's trade logistics infrastructure.", time:"6 min read", body:"Ethiopia's logistics infrastructure is in a phase of rapid transformation. The Addis Ababa\u2013Djibouti railway carries 5 million tons of cargo annually."},
  {id:12, title:"Blockchain for Coffee Traceability", date:"2026-05-28", category:"SUPPLY CHAIN", desc:"Pilot programs demonstrate 30% premium capture for fully traceable lots.", time:"7 min read", body:"Blockchain-based traceability is transforming the Ethiopian coffee supply chain."},
  {id:13, title:"GIS Mapping and Precision Agriculture", date:"2026-06-20", category:"SUPPLY CHAIN", desc:"Satellite imagery deployed across 1.2 million hectares of Ethiopian farmland for precision agriculture, enabling real-time crop monitoring and resource optimization.", time:"5 min read", body:"Precision agriculture is gaining momentum in Ethiopia. Satellite imagery deployed across 1.2 million hectares of farmland enables real-time crop monitoring and resource optimization. Farmers and cooperatives can now access NDVI data, soil moisture analytics, and yield prediction models through mobile platforms.\n\nThe Ethiopian Space Science and Technology Institute has partnered with international agencies to provide free satellite data access to agricultural stakeholders. This initiative covers coffee, sesame, and cereal-growing regions, helping farmers optimize irrigation schedules and fertilizer application. Early adopters report 20-30% reduction in water usage and 15% increase in yields.\n\nThe Ministry of Agriculture has set a target to expand precision agriculture coverage to 5 million hectares by 2028, with particular focus on high-value export crops like coffee and sesame."},
  {id:14, title:"Why Ethiopia is the Next Frontier for Investment", date:"2026-03-10", category:"INVESTMENT", desc:"Ethiopia offers 74 million hectares of arable land and diverse agro-ecological zones.", time:"6 min read", body:"Ethiopia represents one of the last great frontiers for agricultural investment."},
  {id:15, title:"Agri-Fintech Opportunities in Ethiopia", date:"2026-04-22", category:"INVESTMENT", desc:"Only 35% of adults have formal financial access in Ethiopia.", time:"5 min read", body:"Financial inclusion is the single most transformative lever for Ethiopian agriculture."},
  {id:16, title:"Special Economic Zones and Agri-Processing Parks", date:"2026-05-15", category:"INVESTMENT", desc:"Ethiopia's industrial parks include dedicated agro-processing zones.", time:"7 min read", body:"The Industrial Parks Development Corporation manages 13 operational industrial parks."},
  {id:17, title:"Ethiopia's Historic Export Year", date:"2026-07-11", category:"INVESTMENT", desc:"Ethiopia recorded US$10.7 billion in exports, a 29% increase.", time:"6 min read", body:"Ethiopia recorded its highest-ever annual export performance."},
  {id:18, title:"Navigating EUDR Compliance", date:"2026-06-01", category:"INVESTMENT", desc:"The EUDR presents both a compliance burden and a strategic opportunity.", time:"8 min read", body:"The EU Deforestation Regulation requires all commodities entering the EU market to be deforestation-free."},
  {id:19, title:"Land Tenure and Investment Law in Ethiopia", date:"2026-02-20", category:"INVESTMENT", desc:"Understanding Ethiopia's unique land governance system.", time:"7 min read", body:"Under the 1995 Constitution, all land in Ethiopia is owned by the state."},
  {id:20, title:"Logistics Bottlenecks and Port Dependency", date:"2026-04-08", category:"INVESTMENT", desc:"Ethiopia's reliance on the Port of Djibouti for 95% of trade.", time:"6 min read", body:"The Port of Djibouti handles approximately 95% of Ethiopia's maritime trade."}
];


  {cat:'coffee',cl:'Coffee',svg:'<circle cx="30" cy="30" r="18" fill="none" stroke="currentColor" stroke-width="1.5"/>',pts:[{l:'Production 2024/25',v:'8.5M bags (510K t)',d:'Total coffee production — 60% washed, 40% natural',s:'USDA FAS',y:'2025'},{l:'Arabica Share',v:'100%',d:'Ethiopia produces exclusively Coffea arabica',s:'ICO',y:'2025'},{l:'Export Volume 2024/25',v:'4.2M bags',d:'Total export volume (green bean equivalent)',s:'NBE',y:'2025'},{l:'Export Revenue 2025/26',v:'$3B',d:'Record annual coffee export earnings',s:'NBE',y:'2026'},{l:'Smallholder Farmers',v:'5M+',d:'Estimated number of coffee-growing households',s:'CSA',y:'2024'},{l:'Coffee Area',v:'800K ha',d:'Total land under coffee cultivation',s:'CSA',y:'2024'},{l:'Specialty Share',v:'35%',d:'Share of exports meeting specialty grade (SCA 80+)',s:'ECX',y:'2025'},{l:'Average Yield',v:'0.6 t/ha',d:'Low yield due to aging trees and traditional practices',s:'FAO',y:'2024'},{l:'Local Consumption',v:'50%',d:'Approximately half of production is consumed domestically',s:'ICO',y:'2024'},{l:'Export Price Avg 2025',v:'$7.20/kg',d:'Average FOB price for Ethiopian green coffee',s:'ECX',y:'2025'},{l:'Disease Loss',v:'15%',d:'Estimated annual loss to coffee berry disease (CBD)',s:'EIAR',y:'2024'},{l:'Organic Certified',v:'75K ha',d:'Certified organic coffee production area',s:'IFOAM',y:'2024'},{l:'Forest Coffee Share',v:'35%',d:'Share of production from forest and semi-forest systems',s:'CSA',y:'2024'},{l:'Garden Coffee Share',v:'50%',d:'Share from garden coffee systems (with enset, crops)',s:'CSA',y:'2024'},{l:'State Farms Share',v:'5%',d:'Share from state-owned coffee plantations',s:'CSA',y:'2024'}]},
  {cat:'sesame',cl:'Sesame',svg:'<polygon points="15,40 30,5 45,40" fill="none" stroke="currentColor" stroke-width="1.5"/>',pts:[{l:'Production 2024/25',v:'650K t',d:'Total sesame seed production',s:'USDA FAS',y:'2025'},{l:'Export Volume',v:'500K t',d:'Annual sesame export volume',s:'ITC Trademap',y:'2025'},{l:'Export Revenue',v:'$1.2B',d:'Foreign exchange from sesame exports',s:'NBE',y:'2025'},{l:'Global Rank',v:'#2',d:'Second largest sesame exporter after Sudan',s:'ITC Trademap',y:'2025'},{l:'Humera Premium',v:'+20%',d:'Humera-type sesame commands 20% above benchmark',s:'ECX',y:'2025'},{l:'Growing Zones',v:'Tigray, Amhara, Oromia',d:'Three main producing regions',s:'CSA',y:'2024'},{l:'Smallholder Share',v:'90%',d:'Share of production from smallholder farmers',s:'CSA',y:'2024'},{l:'Oil Content',v:'50-55%',d:'Average seed oil content (high quality)',s:'EIAR',y:'2024'},{l:'Main Markets',v:'China, Israel, Turkey, Japan',d:'Largest export destinations',s:'ITC Trademap',y:'2025'},{l:'Yield Avg',v:'0.8 t/ha',d:'Average yield per hectare',s:'FAO',y:'2024'}]},
  {cat:'teff',cl:'Teff &amp; Cereals',svg:'<rect x="10" y="25" width="40" height="2" fill="currentColor" opacity="0.4"/><rect x="15" y="30" width="30" height="2" fill="currentColor" opacity="0.3"/><rect x="12" y="35" width="36" height="2" fill="currentColor" opacity="0.2"/>',pts:[{l:'Teff Production 2025',v:'6.2M t',d:'Record annual teff grain production',s:'CSA',y:'2025'},{l:'Teff Area',v:'3M ha',d:'Total land under teff cultivation',s:'CSA',y:'2025'},{l:'Teff Share of Cereals',v:'28%',d:'Teff as percentage of total cereal production',s:'CSA',y:'2025'},{l:'Total Cereal Production',v:'24M t',d:'All cereals including teff, maize, wheat, barley, sorghum',s:'CSA',y:'2025'},{l:'Maize Production',v:'11M t',d:'Largest cereal crop by volume',s:'CSA',y:'2025'},{l:'Wheat Production',v:'7M t',d:'Second-largest cereal, growing rapidly',s:'CSA',y:'2025'},{l:'Sorghum Production',v:'5M t',d:'Key drought-resistant staple',s:'CSA',y:'2025'},{l:'Teff Yield',v:'1.7 t/ha',d:'Improved variety yields up to 2.5 t/ha',s:'EIAR',y:'2025'},{l:'Teff Export 2025',v:'85K t',d:'Export volume (less than 2% of production)',s:'ITC Trademap',y:'2025'},{l:'Injera Consumption',v:'60% daily',d:'Percentage of population consuming injera daily',s:'CSA',y:'2024'}]},
  {cat:'honey',cl:'Honey',svg:'<polygon points="15,35 30,10 45,35" fill="none" stroke="currentColor" stroke-width="1.5"/><line x1="15" y1="35" x2="15" y2="45" stroke="currentColor" stroke-width="1"/><line x1="45" y1="35" x2="45" y2="45" stroke="currentColor" stroke-width="1"/>',pts:[{l:'Annual Production',v:'65K t',d:'Total honey production — largest in Africa',s:'FAO',y:'2024'},{l:'Africa Rank',v:'#1',d:'Largest honey producer on the continent',s:'FAO',y:'2024'},{l:'Global Rank',v:'#10',d:'Among global honey producers',s:'FAO',y:'2024'},{l:'Export Volume',v:'<3K t',d:'Less than 5% of production exported',s:'ITC Trademap',y:'2025'},{l:'Beehives',v:'2M+',d:'Estimated managed beehives (traditional + modern)',s:'CSA',y:'2024'},{l:'Beekeepers',v:'1.5M',d:'Estimated number of beekeeping households',s:'CSA',y:'2024'},{l:'White Honey Premium',v:'+40%',d:'Premium for high-grade white honey in export markets',s:'EIAR',y:'2024'},{l:'Wax Production',v:'5K t',d:'Annual beeswax production (export commodity)',s:'FAO',y:'2024'}]},
  {cat:'spices',cl:'Spices',svg:'<circle cx="20" cy="25" r="4" fill="currentColor" opacity="0.4"/><circle cx="30" cy="20" r="3" fill="currentColor" opacity="0.3"/><circle cx="35" cy="30" r="5" fill="currentColor" opacity="0.25"/><circle cx="25" cy="35" r="3.5" fill="currentColor" opacity="0.2"/>',pts:[{l:'Commercial Species',v:'20+',d:'Number of commercially traded spice species',s:'EIAR',y:'2024'},{l:'Export Revenue',v:'$120M',d:'Annual spice export earnings',s:'NBE',y:'2025'},{l:'Korarima Production',v:'15K t',d:'Ethiopian cardamom production (Aframomum corrorima)',s:'CSA',y:'2024'},{l:'Black Cumin Export',v:'8K t',d:'Nigella sativa seed export volume',s:'ITC Trademap',y:'2025'},{l:'Berbere Export',v:'2K t',d:'Processed spice blend export volume',s:'ITC Trademap',y:'2025'},{l:'Growing Regions',v:'SNNP, Oromia, Amhara',d:'Main spice-producing regions',s:'CSA',y:'2024'},{l:'Export Growth',v:'+15% YoY',d:'Export value growth rate for spices',s:'NBE',y:'2025'},{l:'Destination Countries',v:'35',d:'Number of countries importing Ethiopian spices',s:'ITC Trademap',y:'2025'}]},
  {cat:'fruits',cl:'Fruits &amp; Veg',svg:'<circle cx="20" cy="25" r="8" fill="none" stroke="currentColor" stroke-width="1.2"/><circle cx="35" cy="22" r="6" fill="none" stroke="currentColor" stroke-width="1"/><circle cx="28" cy="35" r="5" fill="none" stroke="currentColor" stroke-width="0.8"/>',pts:[{l:'Sector Growth',v:'+15% YoY',d:'Annual horticulture export growth rate',s:'NBE',y:'2025'},{l:'Avocado Export Growth',v:'+240%',d:'Growth in avocado export volume 2020-2025',s:'ITC Trademap',y:'2025'},{l:'Avocado Production',v:'150K t',d:'Total avocado production',s:'CSA',y:'2025'},{l:'Cut Flowers Rank',v:'#2 Africa',d:'Second largest cut flower exporter in Africa (after Kenya)',s:'ITC Trademap',y:'2025'},{l:'Fresh Fruit Export',v:'$250M',d:'Annual fresh fruit export value',s:'NBE',y:'2025'},{l:'Vegetable Export',v:'$180M',d:'Annual vegetable export value (incl. frozen)',s:'NBE',y:'2025'},{l:'Irrigated Area',v:'2.5M ha',d:'Estimated irrigable land for horticulture',s:'MoA',y:'2024'},{l:'HH Farmers',v:'200K+',d:'Households engaged in horticulture export',s:'CSA',y:'2024'}]},
  {cat:'livestock',cl:'Livestock',svg:'<rect x="15" y="20" rx="4" width="12" height="18" fill="none" stroke="currentColor" stroke-width="1.2"/><rect x="30" y="15" rx="3" width="14" height="23" fill="none" stroke="currentColor" stroke-width="1"/>',pts:[{l:'Cattle Herd',v:'70M head',d:'Largest cattle herd in Africa',s:'CSA',y:'2024'},{l:'Sheep &amp; Goats',v:'80M head',d:'Combined sheep and goat population',s:'CSA',y:'2024'},{l:'Camels',v:'2.5M head',d:'Largest camel herd outside Horn of Africa',s:'CSA',y:'2024'},{l:'Poultry',v:'60M birds',d:'Estimated poultry population (mostly indigenous)',s:'CSA',y:'2024'},{l:'Milk Production',v:'5B L/year',d:'Annual milk production (90% from traditional systems)',s:'FAO',y:'2024'},{l:'Meat Production',v:'1.5M t',d:'Annual meat production (beef, mutton, goat, camel)',s:'FAO',y:'2024'},{l:'Export Revenue',v:'$450M',d:'Livestock and livestock product export earnings',s:'NBE',y:'2025'},{l:'Live Animal Export',v:'2M head',d:'Annual live animal export to Middle East (incl. informal)',s:'ITC Trademap',y:'2025'},{l:'Leather Export',v:'$150M',d:'Processed leather and leather goods export',s:'NBE',y:'2025'},{l:'Pastoralist Population',v:'12M',d:'Estimated population relying primarily on livestock',s:'CSA',y:'2024'}]},
  {cat:'trade',cl:'Trade &amp; Economy',svg:'<rect x="10" y="30" width="10" height="15" fill="currentColor" opacity="0.3"/><rect x="23" y="20" width="10" height="25" fill="currentColor" opacity="0.4"/><rect x="36" y="25" width="10" height="20" fill="currentColor" opacity="0.35"/>',pts:[{l:'Total Exports 2025/26',v:'$10.7B',d:'Record annual export earnings',s:'NBE',y:'2026'},{l:'Export Growth YoY',v:'+29%',d:'Year-over-year increase in total exports',s:'NBE',y:'2026'},{l:'Coffee Share',v:'30%',d:'Coffee percentage of total export earnings',s:'NBE',y:'2026'},{l:'Gold Share',v:'20%',d:'Gold as share of total exports (~$2.1B)',s:'NBE',y:'2026'},{l:'Sesame Share',v:'11%',d:'Sesame as share of total exports (~$1.2B)',s:'NBE',y:'2026'},{l:'China Trade',v:'$7B+',d:'Bilateral trade with China (exports + imports)',s:'IMF DOTS',y:'2025'},{l:'Top Export Destination',v:'China',d:'Largest single export destination',s:'ITC Trademap',y:'2025'},{l:'EU Export Share',v:'25%',d:'Share of exports destined for the European Union',s:'ITC Trademap',y:'2025'},{l:'Trade Deficit',v:'-$15B',d:'Estimated annual merchandise trade deficit',s:'NBE',y:'2025'},{l:'Foreign Reserves',v:'$3.5B',d:'Gross international reserves (approx.1.5 months imports)',s:'IMF',y:'2025'},{l:'Inflation (Food)',v:'25%',d:'Food inflation rate (headline CPI ~20%)',s:'CSA',y:'2025'},{l:'GDP Growth',v:'6.5%',d:'Real GDP growth rate (2024/25 estimate)',s:'IMF WEO',y:'2025'}]},
  {cat:'land',cl:'Land &amp; Env.',svg:'<rect x="10" y="20" width="40" height="25" rx="2" fill="none" stroke="currentColor" stroke-width="1.2"/><path d="M15 28 Q30 35 45 28" fill="none" stroke="currentColor" stroke-width="0.8" opacity="0.4"/>',pts:[{l:'Total Area',v:'1.1M km²',d:'Ethiopia is the 27th largest country by area',s:'CSA',y:'2024'},{l:'Arable Land',v:'74M ha',d:'Total arable land potential (currently ~20M used)',s:'MoA',y:'2024'},{l:'Cultivated Area',v:'20M ha',d:'Total land currently under cultivation',s:'CSA',y:'2024'},{l:'Agro-ecological Zones',v:'18',d:'Distinct farming systems across altitude/climate zones',s:'EIAR',y:'2024'},{l:'Highland Share',v:'45%',d:'Land area above 1,500m where most crops are grown',s:'CSA',y:'2024'},{l:'Irrigation Potential',v:'5M ha',d:'Land suitable for irrigation (currently <1M developed)',s:'MoA',y:'2024'},{l:'Irrigated Area',v:'900K ha',d:'Currently irrigated agricultural land',s:'CSA',y:'2024'},{l:'Forest Cover',v:'15%',d:'Percentage of land area under forest (17.3M ha)',s:'FAO',y:'2024'},{l:'Rainfall (Highlands)',v:'1,200-2,500mm/yr',d:'Annual rainfall range in main agricultural zones',s:'NMA',y:'2024'},{l:'Rainfall (Lowlands)',v:'200-600mm/yr',d:'Annual rainfall in pastoral and agro-pastoral zones',s:'NMA',y:'2024'}]},
  {cat:'demo',cl:'Demographics',svg:'<circle cx="30" cy="22" r="8" fill="none" stroke="currentColor" stroke-width="1.2"/><path d="M15 42 Q15 32 22 28 Q30 24 38 28 Q45 32 45 42" fill="none" stroke="currentColor" stroke-width="1"/>',pts:[{l:'Population 2025',v:'132M',d:'Estimated total population (2nd most populous in Africa)',s:'CSA',y:'2025'},{l:'Rural Share',v:'78%',d:'Percentage of population living in rural areas',s:'CSA',y:'2025'},{l:'Ag Labor Force',v:'70%',d:'Share of labor force employed in agriculture',s:'World Bank',y:'2024'},{l:'Under 25 Share',v:'60%',d:'Percentage of population under age 25',s:'CSA',y:'2025'},{l:'Farm Size Avg',v:'<1 ha',d:'Average smallholder farm size',s:'CSA',y:'2024'},{l:'Food Insecure',v:'20M',d:'Estimated population facing acute food insecurity',s:'WFP',y:'2025'},{l:'Population Growth',v:'2.5%/yr',d:'Annual population growth rate',s:'CSA',y:'2025'},{l:'Urbanization Rate',v:'4.5%/yr',d:'Annual urban growth rate (fastest in Africa)',s:'World Bank',y:'2025'}]},
  {cat:'other',cl:'Other Commodities',svg:'<polygon points="20,15 35,15 40,30 15,30" fill="none" stroke="currentColor" stroke-width="1.2"/><line x1="27" y1="20" x2="27" y2="35" stroke="currentColor" stroke-width="0.8"/>',pts:[{l:'Khat Production',v:'350K t',d:'Estimated annual khat (chat) leaf production',s:'CSA',y:'2024'},{l:'Khat Export Revenue',v:'$400M',d:'Estimated annual export earnings from khat',s:'NBE',y:'2025'},{l:'Sugar Production',v:'500K t',d:'Refined sugar production (from state-owned factories)',s:'Sugar Corp',y:'2025'},{l:'Cut Flower Export',v:'$350M',d:'Annual cut flower export value',s:'NBE',y:'2025'},{l:'Cotton Production',v:'60K t',d:'Annual cotton fiber production',s:'CSA',y:'2024'},{l:'Cotton Import',v:'$50M',d:'Cotton and textile raw material imports',s:'ITC Trademap',y:'2025'}]}
];


  {c:'Teff',g:'Cereals',r:'Amhara, Oromia, SNNP',sw:[7,8],hv:[11,12]},
  {c:'Maize (Meher)',g:'Cereals',r:'Oromia, Amhara, SNNP',sw:[6,7],hv:[10,12]},
  {c:'Maize (Belg)',g:'Cereals',r:'SNNP, Oromia',sw:[3,4],hv:[7,8]},
  {c:'Wheat',g:'Cereals',r:'Oromia, Amhara, Tigray',sw:[6,7],hv:[10,11]},
  {c:'Barley',g:'Cereals',r:'Amhara, Oromia, Tigray',sw:[6,7],hv:[10,11]},
  {c:'Sorghum (Meher)',g:'Cereals',r:'Amhara, Tigray, Oromia',sw:[6,7],hv:[11,12]},
  {c:'Chickpeas',g:'Pulses',r:'Amhara, Oromia, SNNP',sw:[8,9],hv:[12,1]},
  {c:'Lentils',g:'Pulses',r:'Amhara, Oromia',sw:[7,8],hv:[11,12]},
  {c:'Faba Beans',g:'Pulses',r:'Amhara, Oromia, Tigray',sw:[6,7],hv:[10,11]},
  {c:'Haricot Beans',g:'Pulses',r:'Amhara, Oromia, SNNP',sw:[7,8],hv:[10,11]},
  {c:'Sesame',g:'Oilseeds',r:'Tigray, Amhara, Oromia',sw:[6,7],hv:[10,11]},
  {c:'Groundnuts',g:'Oilseeds',r:'Oromia, Amhara, Tigray',sw:[6,7],hv:[10,11]},
  {c:'Coffee Arabica',g:'Cash Crops',r:'Oromia, SNNP, Sidama',hv:[10,1],note:'Perennial'},
  {c:'Cotton',g:'Cash Crops',r:'Amhara, Oromia, Afar',sw:[6,7],hv:[11,1]},
  {c:'Sugarcane',g:'Cash Crops',r:'Afar, Amhara, SNNP',note:'12-18mo cycle, year-round harvest'},
  {c:'Avocado',g:'Fruits',r:'SNNP, Oromia',hv:[5,9],note:'Perennial'},
  {c:'Mango',g:'Fruits',r:'SNNP, Oromia, Afar',hv:[5,8],note:'Perennial'},
  {c:'Banana',g:'Fruits',r:'SNNP, Oromia',note:'Perennial, year-round harvest'},
  {c:'Grapes',g:'Fruits',r:'Tigray, Amhara',hv:[8,10]},
  {c:'Khat',g:'Cash Crops',r:'Oromia, SNNP',note:'Year-round harvest'},
];
var SEASONS_CATS = ['Cereals','Pulses','Oilseeds','Cash Crops','Fruits'];
var REGION_SOURCE = {
  coffee:{
    'Production 2024/25':{r:'Oromia/SNNP/Sidama',st:'official'},'Arabica Share':{r:'National',st:'official'},'Export Volume 2024/25':{r:'National',st:'official'},'Export Revenue 2025/26':{r:'National',st:'official'},'Smallholder Farmers':{r:'National',st:'official'},'Coffee Area':{r:'Oromia/SNNP',st:'official'},'Specialty Share':{r:'Sidama/Yirgacheffe',st:'estimate'},'Average Yield':{r:'National',st:'official'},'Local Consumption':{r:'National',st:'estimate'},'Export Price Avg 2025':{r:'National',st:'official'},'Disease Loss':{r:'National',st:'estimate'},'Organic Certified':{r:'Sidama/Yirgacheffe',st:'official'},
    'Forest Coffee Share':{r:'Kaffa/Bench-Maji',st:'estimate'},'Garden Coffee Share':{r:'Sidama/SNNP',st:'estimate'},'State Farms Share':{r:'National',st:'official'}
  },
  sesame:{
    'Production 2024/25':{r:'Tigray/Amhara',st:'official'},'Export Volume':{r:'National',st:'official'},'Export Revenue':{r:'National',st:'official'},'Global Rank':{r:'National',st:'official'},'Humera Premium':{r:'Tigray/Humera',st:'estimate'},'Growing Zones':{r:'Tigray/Amhara/Oromia',st:'official'},'Smallholder Share':{r:'National',st:'official'},'Oil Content':{r:'National',st:'official'},'Main Markets':{r:'National',st:'official'},'Yield Avg':{r:'National',st:'official'}
  },
  teff:{
    'Teff Production 2025':{r:'Amhara/Oromia',st:'official'},'Teff Area':{r:'Amhara/Oromia/SNNP',st:'official'},'Teff Share of Cereals':{r:'National',st:'official'},'Total Cereal Production':{r:'National',st:'official'},'Maize Production':{r:'Oromia/Amhara',st:'official'},'Wheat Production':{r:'Oromia/Amhara',st:'official'},'Sorghum Production':{r:'Amhara/Tigray',st:'official'},'Teff Yield':{r:'National',st:'estimate'},'Teff Export 2025':{r:'National',st:'official'},'Injera Consumption':{r:'National',st:'estimate'}
  },
  honey:{
    'Annual Production':{r:'Tigray/SNNP',st:'official'},'Africa Rank':{r:'National',st:'official'},'Global Rank':{r:'National',st:'official'},'Export Volume':{r:'National',st:'official'},'Beehives':{r:'National',st:'estimate'},'Beekeepers':{r:'National',st:'estimate'},'White Honey Premium':{r:'Tigray',st:'estimate'},'Wax Production':{r:'National',st:'official'}
  },
  spices:{
    'Commercial Species':{r:'National',st:'official'},'Export Revenue':{r:'National',st:'official'},'Korarima Production':{r:'SNNP/Bale',st:'official'},'Black Cumin Export':{r:'Amhara/SNNP',st:'official'},'Berbere Export':{r:'National',st:'official'},'Growing Regions':{r:'SNNP/Oromia/Amhara',st:'official'},'Export Growth':{r:'National',st:'official'},'Destination Countries':{r:'National',st:'official'}
  },
  fruits:{
    'Sector Growth':{r:'National',st:'official'},'Avocado Export Growth':{r:'SNNP/Oromia',st:'official'},'Avocado Production':{r:'SNNP/Oromia',st:'official'},'Cut Flowers Rank':{r:'National',st:'official'},'Fresh Fruit Export':{r:'National',st:'official'},'Vegetable Export':{r:'National',st:'official'},'Irrigated Area':{r:'Rift Valley',st:'official'},'HH Farmers':{r:'National',st:'official'}
  },
  livestock:{
    'Cattle Herd':{r:'Oromia/Amhara/SNNP',st:'official'},'Sheep & Goats':{r:'Somali/Afar/Oromia',st:'official'},'Camels':{r:'Somali/Afar',st:'official'},'Poultry':{r:'National',st:'estimate'},'Milk Production':{r:'National',st:'official'},'Meat Production':{r:'National',st:'official'},'Export Revenue':{r:'National',st:'official'},'Live Animal Export':{r:'Somali/Afar',st:'official'},'Leather Export':{r:'National',st:'official'},'Pastoralist Population':{r:'Somali/Afar/Oromia',st:'estimate'}
  },
  trade:{
    'Total Exports 2025/26':{r:'National',st:'official'},'Export Growth YoY':{r:'National',st:'official'},'Coffee Share':{r:'National',st:'official'},'Gold Share':{r:'National',st:'official'},'Sesame Share':{r:'National',st:'official'},'China Trade':{r:'National',st:'official'},'Top Export Destination':{r:'National',st:'official'},'EU Export Share':{r:'National',st:'official'},'Trade Deficit':{r:'National',st:'official'},'Foreign Reserves':{r:'National',st:'official'},'Inflation (Food)':{r:'National',st:'official'},'GDP Growth':{r:'National',st:'estimate'}
  },
  land:{
    'Total Area':{r:'National',st:'official'},'Arable Land':{r:'National',st:'official'},'Cultivated Area':{r:'National',st:'official'},'Agro-ecological Zones':{r:'National',st:'official'},'Highland Share':{r:'National',st:'official'},'Irrigation Potential':{r:'National',st:'estimate'},'Irrigated Area':{r:'National',st:'official'},'Forest Cover':{r:'National',st:'official'},'Rainfall (Highlands)':{r:'Highlands',st:'official'},'Rainfall (Lowlands)':{r:'Lowlands',st:'official'}
  },
  demo:{
    'Population 2025':{r:'National',st:'official'},'Rural Share':{r:'National',st:'official'},'Ag Labor Force':{r:'National',st:'official'},'Under 25 Share':{r:'National',st:'official'},'Farm Size Avg':{r:'National',st:'official'},'Food Insecure':{r:'Tigray/Amhara/Somali',st:'estimate'},'Population Growth':{r:'National',st:'official'},'Urbanization Rate':{r:'National',st:'estimate'}
  },
  other:{
    'Khat Production':{r:'Oromia/SNNP',st:'estimate'},'Khat Export Revenue':{r:'National',st:'estimate'},'Sugar Production':{r:'Afar/Amhara',st:'official'},'Cut Flower Export':{r:'National',st:'official'},'Cotton Production':{r:'Amhara/Oromia',st:'official'},'Cotton Import':{r:'National',st:'official'}
  }
};

var DATA_ILLS = {
  coffee:'<circle cx="30" cy="25" r="14" fill="none" stroke="currentColor" stroke-width="1"/><path d="M20 35 L24 42 L36 42 L40 35" fill="none" stroke="currentColor" stroke-width="0.8"/><path d="M28 42 L28 48 M32 42 L32 48" stroke="currentColor" stroke-width="0.6"/>',
  sesame:'<polygon points="15,38 30,7 45,38" fill="none" stroke="currentColor" stroke-width="1"/><line x1="30" y1="7" x2="30" y2="45" stroke="currentColor" stroke-width="0.5" opacity="0.3"/>',
  teff:'<rect x="10" y="28" width="40" height="1.5" fill="currentColor" opacity="0.3"/><rect x="14" y="32" width="32" height="1.5" fill="currentColor" opacity="0.25"/><rect x="12" y="36" width="36" height="1.5" fill="currentColor" opacity="0.2"/><rect x="18" y="40" width="24" height="1.5" fill="currentColor" opacity="0.15"/>',
  honey:'<polygon points="15,38 30,7 45,38" fill="none" stroke="currentColor" stroke-width="1"/><line x1="30" y1="7" x2="30" y2="45" stroke="currentColor" stroke-width="0.5" opacity="0.3"/><circle cx="30" cy="25" r="8" fill="none" stroke="currentColor" stroke-width="0.6" opacity="0.4"/>',
  spices:'<circle cx="20" cy="25" r="5" fill="currentColor" opacity="0.4"/><circle cx="30" cy="20" r="4" fill="currentColor" opacity="0.3"/><circle cx="35" cy="30" r="6" fill="currentColor" opacity="0.25"/><circle cx="25" cy="35" r="4" fill="currentColor" opacity="0.2"/>',
  fruits:'<circle cx="20" cy="25" r="10" fill="none" stroke="currentColor" stroke-width="1"/><circle cx="35" cy="22" r="7" fill="none" stroke="currentColor" stroke-width="0.8"/><circle cx="28" cy="36" r="6" fill="none" stroke="currentColor" stroke-width="0.6"/>',
  livestock:'<rect x="16" y="18" rx="3" width="12" height="22" fill="none" stroke="currentColor" stroke-width="1"/><rect x="32" y="12" rx="2" width="12" height="28" fill="none" stroke="currentColor" stroke-width="1"/>',
  trade:'<rect x="10" y="30" width="10" height="15" fill="currentColor" opacity="0.25"/><rect x="23" y="20" width="10" height="25" fill="currentColor" opacity="0.35"/><rect x="36" y="25" width="10" height="20" fill="currentColor" opacity="0.3"/>',
  land:'<rect x="12" y="18" width="36" height="26" rx="2" fill="none" stroke="currentColor" stroke-width="1"/><path d="M18 28 Q30 34 42 28" fill="none" stroke="currentColor" stroke-width="0.7" opacity="0.4"/>',
  demo:'<circle cx="30" cy="20" r="10" fill="none" stroke="currentColor" stroke-width="1"/><path d="M14 44 Q14 32 22 28 Q30 24 38 28 Q46 32 46 44" fill="none" stroke="currentColor" stroke-width="1"/>',
  other:'<polygon points="20,15 40,15 45,30 15,30" fill="none" stroke="currentColor" stroke-width="1"/><line x1="30" y1="18" x2="30" y2="38" stroke="currentColor" stroke-width="0.7"/>'
};

var DATA_CAT_ORDER = ['coffee','sesame','teff','honey','spices','fruits','livestock','trade','land','demo','other'];

var savedView = JSON.parse(localStorage.getItem('drSavedView') || 'null');
var hiddenCats = JSON.parse(localStorage.getItem('drHiddenCats') || '[]');

  'investment-zones-incentives': { title:'Zones &amp; Potential', desc:'13 operational industrial parks including dedicated agro-processing zones with tax holidays.', filter:'INVESTMENT' },
  'investment-challenges': { title:'Challenges', desc:'Understanding land governance and infrastructure constraints is essential for successful investment.', filter:'INVESTMENT' },
  'about': { title:'About', desc:'AgroSpace Ethiopia provides market intelligence and supply chain analysis for Ethiopian agricultural exports.', html:'<div class="page-grid-2" style="grid-template-columns:repeat(2,1fr)"><a href="#" onclick="navigateTo(\'about-mission\');return false" class="page-card"><h3>Our mission</h3><p>Empowering data-driven decisions</p></a><a href="#" onclick="navigateTo(\'about-platform\');return false" class="page-card"><h3>The platform</h3><p>How our system works</p></a></div>' },
  'about-mission': { title:'Our Mission', desc:'To provide comprehensive market intelligence that empowers stakeholders across Ethiopia\'s agricultural value chain.', html:'<div class="page-static"><div class="section"><p>Deliver real-time market analysis for Ethiopian export sectors</p></div><div class="section"><p>Bridge the information gap between producers and global markets</p></div><div class="section"><p>Promote transparency in supply chain operations</p></div><div class="section"><p>Support sustainable agricultural practices through data</p></div><div class="section"><p>Facilitate investment through actionable sector insights</p></div></div>' },
  'about-platform': { title:'The Platform', desc:'A comprehensive market intelligence platform combining data analytics, supply chain tracking, and sector analysis.', html:'<div class="page-static"><div class="section"><p>Multi-sector article database with search and filter capabilities</p></div><div class="section"><p>Interactive data dashboards with export statistics</p></div><div class="section"><p>Supply chain traceability tools including EUDR compliance</p></div><div class="section"><p>Investment analysis with zone and incentive mapping</p></div><div class="section"><p>Real-time market indicators and trend tracking</p></div></div>' },
  'about-team': { title:'Team', desc:'The analysts, researchers, and technologists building Ethiopia\'s agricultural market intelligence platform.', html:'<div class="page-static"><div class="author"><div class="author-avatar">AE</div><div class="author-info"><span class="author-name">AgroSpace Ethiopia</span><span class="author-role">Market Intelligence Unit</span></div></div><div class="author"><div class="author-avatar">SK</div><div class="author-info"><span class="author-name">Saba Kebede</span><span class="author-role">Lead Analyst, Coffee Sector</span></div></div><div class="author"><div class="author-avatar">MT</div><div class="author-info"><span class="author-name">Mekdes Tilahun</span><span class="author-role">Supply Chain Researcher</span></div></div><div class="author"><div class="author-avatar">BH</div><div class="author-info"><span class="author-name">Biruk Hailu</span><span class="author-role">Data Scientist &amp; GIS Specialist</span></div></div><div class="author"><div class="author-avatar">AW</div><div class="author-info"><span class="author-name">Azeb Wondimu</span><span class="author-role">Investment &amp; Policy Analyst</span></div></div></div>' },
  'about-careers': { title:'Careers', desc:'Join our team of professionals working at the intersection of agriculture, data, and market intelligence.', html:'<div class="page-static"><div class="section"><p>Market Analyst &mdash; Coffee and beverage crops</p></div><div class="section"><p>Supply Chain Researcher &mdash; Logistics and compliance</p></div><div class="section"><p>Data Engineer &mdash; Pipeline and dashboard development</p></div><div class="section"><p>Policy Researcher &mdash; Trade and investment regulation</p></div><div class="section"><p>Communications Lead &mdash; Content and outreach</p></div></div>' },
  'data': { title:'Data Room', desc:'Export statistics, market indicators, and interactive data for Ethiopian agricultural sectors.', html:'<div id="dataroom" class="data-room"></div>' },
  'contact': { title:'Contact', desc:'Get in touch with the AgroSpace Ethiopia team.', html:'<div style="display:grid;grid-template-columns:1fr 1fr;gap:32px;margin-top:24px"><div><h3 style="font-size:14px;font-weight:600">Email</h3><p style="font-size:12px;color:var(--emerald);margin-top:4px">agrospace.eth@gmail.com</p></div><div><h3 style="font-size:14px;font-weight:600">Location</h3><p style="font-size:12px;color:var(--text);margin-top:4px">Addis Ababa, Ethiopia</p></div></div><div style="margin-top:32px;padding:32px;border:1px solid var(--pastel);border-radius:12px"><div style="display:flex;align-items:center;gap:12px;margin-bottom:20px"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--emerald)" stroke-width="1.5"><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg><h3 style="font-size:14px;font-weight:600">Send a message</h3></div><div style="display:grid;gap:16px"><input type="text" placeholder="Your name" style="padding:12px 16px;border:1px solid var(--pastel);border-radius:10px;font-family:Jost;font-size:12px;outline:none;transition:border-color 0.3s" onfocus="this.style.borderColor=\'var(--emerald)\'" onblur="this.style.borderColor=\'\'"><input type="email" placeholder="Your email" style="padding:12px 16px;border:1px solid var(--pastel);border-radius:10px;font-family:Jost;font-size:12px;outline:none;transition:border-color 0.3s" onfocus="this.style.borderColor=\'var(--emerald)\'" onblur="this.style.borderColor=\'\'"><textarea placeholder="Your message" rows="5" style="padding:12px 16px;border:1px solid var(--pastel);border-radius:10px;font-family:Jost;font-size:12px;outline:none;resize:vertical;transition:border-color 0.3s" onfocus="this.style.borderColor=\'var(--emerald)\'" onblur="this.style.borderColor=\'\'"></textarea><button style="padding:12px 24px;background:var(--emerald);color:var(--white);border:none;border-radius:10px;font-family:Jost;font-size:11px;font-weight:600;letter-spacing:2px;text-transform:uppercase;cursor:pointer;width:fit-content;transition:background 0.3s" onmouseover="this.style.background=\'#1B4332\'" onmouseout="this.style.background=\'\'">Send message</button></div></div>' }
};



var galleryData = [
  { title:"Ethiopia's $6B Coffee Ambition", desc:"Coffee &middot; July 4, 2026 &middot; 7 min read", svg:'<svg viewBox="0 0 800 500"><rect width="800" height="500" fill="#C5DFC9"/><circle cx="400" cy="250" r="120" fill="#2E8B57" opacity="0.12"/></svg>' },
  { title:"Germany's Coffee Revolution", desc:"Coffee &middot; May 18, 2026 &middot; 7 min read", svg:'<svg viewBox="0 0 800 500"><rect width="800" height="500" fill="#8DBC76" opacity="0.4"/><rect x="100" y="160" width="600" height="1" fill="#2E8B57" opacity="0.3"/></svg>' },
  { title:"Teff: Ethiopia's Super Grain", desc:"Teff &middot; Feb 28, 2026 &middot; 6 min read", svg:'<svg viewBox="0 0 800 500"><rect width="800" height="500" fill="#C5DFC9"/><rect x="120" y="180" width="560" height="120" rx="4" fill="#2E8B57" opacity="0.12"/></svg>' }
];
var currentIdx = 0;